import json
import os

challenges = []

# Problem 41
c41 = {
    "problemNumber": 41,
    "title": "Implement Queue using Stacks",
    "slug": "implement-queue-using-stacks",
    "difficulty": "Easy",
    "category": "Queue",
    "description": "Implement a first in first out (FIFO) queue using only two stacks. The implemented queue should support all the functions of a normal queue (`push`, `peek`, `pop`, and `empty`).\n\nImplement the `MyQueue` class:\n\n* `void push(int x)` Pushes element x to the back of the queue.\n* `int pop()` Removes the element from the front of the queue and returns it.\n* `int peek()` Returns the element at the front of the queue.\n* `boolean empty()` Returns `true` if the queue is empty, `false` otherwise.",
    "examples": [
        {
            "input": "6\nMyQueue\npush 1\npush 2\npeek\npop\nempty",
            "output": "null\nnull\nnull\n1\n1\nfalse",
            "explanation": "MyQueue myQueue = new MyQueue();\nmyQueue.push(1); // queue is: [1]\nmyQueue.push(2); // queue is: [1, 2] (leftmost is front of the queue)\nmyQueue.peek(); // return 1\nmyQueue.pop(); // return 1, queue is [2]\nmyQueue.empty(); // return false"
        }
    ],
    "constraints": [
        "1 <= x <= 9",
        "At most 100 calls will be made to push, pop, peek, and empty.",
        "All the calls to pop and peek are valid."
    ],
    "publicTestCases": [
        {"input": "6\nMyQueue\npush 1\npush 2\npeek\npop\nempty", "expectedOutput": "null\nnull\nnull\n1\n1\nfalse"},
        {"input": "3\nMyQueue\npush 5\npop", "expectedOutput": "null\nnull\n5"},
        {"input": "5\nMyQueue\nempty\npush 1\nempty\npop", "expectedOutput": "null\ntrue\nnull\nfalse\n1"}
    ],
    "hiddenTestCases": [
        {"input": "4\nMyQueue\npush 9\npush 8\npop", "expectedOutput": "null\nnull\nnull\n9"},
        {"input": "7\nMyQueue\npush 1\npush 2\npush 3\npop\npop\nempty", "expectedOutput": "null\nnull\nnull\nnull\n1\n2\nfalse"},
        {"input": "8\nMyQueue\npush 1\npop\npush 2\npop\npush 3\npop\nempty", "expectedOutput": "null\nnull\n1\nnull\n2\nnull\n3\ntrue"},
        {"input": "2\nMyQueue\nempty", "expectedOutput": "null\ntrue"},
        {"input": "7\nMyQueue\npush 4\npush 5\npeek\npeek\npop\nempty", "expectedOutput": "null\nnull\nnull\n4\n4\n4\nfalse"}
    ],
    "starterCode": {
        "python": "import sys\n\nclass MyQueue:\n    def __init__(self):\n        pass\n    def push(self, x: int) -> None:\n        pass\n    def pop(self) -> int:\n        pass\n    def peek(self) -> int:\n        pass\n    def empty(self) -> bool:\n        pass\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    obj = None\n    for i in range(1, n + 1):\n        parts = lines[i].split()\n        cmd = parts[0]\n        if cmd == 'MyQueue':\n            obj = MyQueue()\n            print('null')\n        elif cmd == 'push':\n            obj.push(int(parts[1]))\n            print('null')\n        elif cmd == 'pop':\n            print(obj.pop())\n        elif cmd == 'peek':\n            print(obj.peek())\n        elif cmd == 'empty':\n            print('true' if obj.empty() else 'false')\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nclass MyQueue {\npublic:\n    MyQueue() {}\n    void push(int x) {}\n    int pop() { return 0; }\n    int peek() { return 0; }\n    bool empty() { return false; }\n};\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    MyQueue* obj = nullptr;\n    for (int i = 0; i < n; ++i) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"MyQueue\") {\n            obj = new MyQueue();\n            cout << \"null\\n\";\n        } else if (cmd == \"push\") {\n            int x; cin >> x;\n            obj->push(x);\n            cout << \"null\\n\";\n        } else if (cmd == \"pop\") {\n            cout << obj->pop() << \"\\n\";\n        } else if (cmd == \"peek\") {\n            cout << obj->peek() << \"\\n\";\n        } else if (cmd == \"empty\") {\n            cout << (obj->empty() ? \"true\" : \"false\") << \"\\n\";\n        }\n    }\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdbool.h>\n\ntypedef struct {\n    \n} MyQueue;\n\nMyQueue* myQueueCreate() {\n    return NULL;\n}\nvoid myQueuePush(MyQueue* obj, int x) {}\nint myQueuePop(MyQueue* obj) { return 0; }\nint myQueuePeek(MyQueue* obj) { return 0; }\nbool myQueueEmpty(MyQueue* obj) { return false; }\nvoid myQueueFree(MyQueue* obj) {}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    MyQueue* obj = NULL;\n    for (int i = 0; i < n; ++i) {\n        char cmd[20];\n        scanf(\"%s\", cmd);\n        if (strcmp(cmd, \"MyQueue\") == 0) {\n            obj = myQueueCreate();\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"push\") == 0) {\n            int x; scanf(\"%d\", &x);\n            myQueuePush(obj, x);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"pop\") == 0) {\n            printf(\"%d\\n\", myQueuePop(obj));\n        } else if (strcmp(cmd, \"peek\") == 0) {\n            printf(\"%d\\n\", myQueuePeek(obj));\n        } else if (strcmp(cmd, \"empty\") == 0) {\n            printf(\"%s\\n\", myQueueEmpty(obj) ? \"true\" : \"false\");\n        }\n    }\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass MyQueue {\n    public MyQueue() {}\n    public void push(int x) {}\n    public int pop() { return 0; }\n    public int peek() { return 0; }\n    public boolean empty() { return false; }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        MyQueue obj = null;\n        for (int i = 0; i < n; i++) {\n            String cmd = sc.next();\n            if (cmd.equals(\"MyQueue\")) {\n                obj = new MyQueue();\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"push\")) {\n                int x = sc.nextInt();\n                obj.push(x);\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"pop\")) {\n                System.out.println(obj.pop());\n            } else if (cmd.equals(\"peek\")) {\n                System.out.println(obj.peek());\n            } else if (cmd.equals(\"empty\")) {\n                System.out.println(obj.empty() ? \"true\" : \"false\");\n            }\n        }\n    }\n}"
    },
    "optimalSolutions": {
        "python": "import sys\n\nclass MyQueue:\n    def __init__(self):\n        self.s1 = []\n        self.s2 = []\n    def push(self, x: int) -> None:\n        self.s1.append(x)\n    def pop(self) -> int:\n        self.peek()\n        return self.s2.pop()\n    def peek(self) -> int:\n        if not self.s2:\n            while self.s1:\n                self.s2.append(self.s1.pop())\n        return self.s2[-1]\n    def empty(self) -> bool:\n        return not self.s1 and not self.s2\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    obj = None\n    for i in range(1, n + 1):\n        parts = lines[i].split()\n        cmd = parts[0]\n        if cmd == 'MyQueue':\n            obj = MyQueue()\n            print('null')\n        elif cmd == 'push':\n            obj.push(int(parts[1]))\n            print('null')\n        elif cmd == 'pop':\n            print(obj.pop())\n        elif cmd == 'peek':\n            print(obj.peek())\n        elif cmd == 'empty':\n            print('true' if obj.empty() else 'false')\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\n\nclass MyQueue {\n    stack<int> s1, s2;\npublic:\n    MyQueue() {}\n    void push(int x) {\n        s1.push(x);\n    }\n    int pop() {\n        peek();\n        int val = s2.top();\n        s2.pop();\n        return val;\n    }\n    int peek() {\n        if (s2.empty()) {\n            while (!s1.empty()) {\n                s2.push(s1.top());\n                s1.pop();\n            }\n        }\n        return s2.top();\n    }\n    bool empty() {\n        return s1.empty() && s2.empty();\n    }\n};\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    MyQueue* obj = nullptr;\n    for (int i = 0; i < n; ++i) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"MyQueue\") {\n            obj = new MyQueue();\n            cout << \"null\\n\";\n        } else if (cmd == \"push\") {\n            int x; cin >> x;\n            obj->push(x);\n            cout << \"null\\n\";\n        } else if (cmd == \"pop\") {\n            cout << obj->pop() << \"\\n\";\n        } else if (cmd == \"peek\") {\n            cout << obj->peek() << \"\\n\";\n        } else if (cmd == \"empty\") {\n            cout << (obj->empty() ? \"true\" : \"false\") << \"\\n\";\n        }\n    }\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdbool.h>\n\ntypedef struct {\n    int *s1;\n    int *s2;\n    int top1;\n    int top2;\n} MyQueue;\n\nMyQueue* myQueueCreate() {\n    MyQueue* obj = (MyQueue*)malloc(sizeof(MyQueue));\n    obj->s1 = (int*)malloc(200 * sizeof(int));\n    obj->s2 = (int*)malloc(200 * sizeof(int));\n    obj->top1 = -1;\n    obj->top2 = -1;\n    return obj;\n}\nvoid myQueuePush(MyQueue* obj, int x) {\n    obj->s1[++(obj->top1)] = x;\n}\nint myQueuePeek(MyQueue* obj) {\n    if (obj->top2 == -1) {\n        while (obj->top1 != -1) {\n            obj->s2[++(obj->top2)] = obj->s1[(obj->top1)--];\n        }\n    }\n    return obj->s2[obj->top2];\n}\nint myQueuePop(MyQueue* obj) {\n    myQueuePeek(obj);\n    return obj->s2[(obj->top2)--];\n}\nbool myQueueEmpty(MyQueue* obj) {\n    return obj->top1 == -1 && obj->top2 == -1;\n}\nvoid myQueueFree(MyQueue* obj) {\n    free(obj->s1);\n    free(obj->s2);\n    free(obj);\n}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    MyQueue* obj = NULL;\n    for (int i = 0; i < n; ++i) {\n        char cmd[20];\n        scanf(\"%s\", cmd);\n        if (strcmp(cmd, \"MyQueue\") == 0) {\n            obj = myQueueCreate();\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"push\") == 0) {\n            int x; scanf(\"%d\", &x);\n            myQueuePush(obj, x);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"pop\") == 0) {\n            printf(\"%d\\n\", myQueuePop(obj));\n        } else if (strcmp(cmd, \"peek\") == 0) {\n            printf(\"%d\\n\", myQueuePeek(obj));\n        } else if (strcmp(cmd, \"empty\") == 0) {\n            printf(\"%s\\n\", myQueueEmpty(obj) ? \"true\" : \"false\");\n        }\n    }\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass MyQueue {\n    Stack<Integer> s1 = new Stack<>();\n    Stack<Integer> s2 = new Stack<>();\n    public MyQueue() {}\n    public void push(int x) {\n        s1.push(x);\n    }\n    public int pop() {\n        peek();\n        return s2.pop();\n    }\n    public int peek() {\n        if (s2.empty()) {\n            while (!s1.empty()) {\n                s2.push(s1.pop());\n            }\n        }\n        return s2.peek();\n    }\n    public boolean empty() {\n        return s1.empty() && s2.empty();\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        MyQueue obj = null;\n        for (int i = 0; i < n; i++) {\n            String cmd = sc.next();\n            if (cmd.equals(\"MyQueue\")) {\n                obj = new MyQueue();\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"push\")) {\n                int x = sc.nextInt();\n                obj.push(x);\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"pop\")) {\n                System.out.println(obj.pop());\n            } else if (cmd.equals(\"peek\")) {\n                System.out.println(obj.peek());\n            } else if (cmd.equals(\"empty\")) {\n                System.out.println(obj.empty() ? \"true\" : \"false\");\n            }\n        }\n    }\n}"
    },
    "tags": ["Stack", "Design", "Queue"],
    "hints": ["Use one stack to act as the back of the queue and the other as the front.", "Move elements from one stack to another when the front stack is empty."],
    "timeLimit": 2000,
    "memoryLimit": 256000
}

challenges.append(c41)

# I will write similar generators for the rest of the 9 problems inside another script to break it up, or just keep generating.
