import json

challenges = []

c49 = {
    "problemNumber": 49,
    "title": "Design Browser History",
    "slug": "design-browser-history",
    "difficulty": "Medium",
    "category": "Mixed",
    "description": "You have a **browser** of one tab where you start on the `homepage` and you can visit another `url`, get back in the history number of `steps` or move forward in the history number of `steps`.\n\nImplement the `BrowserHistory` class:\n\n* `BrowserHistory(string homepage)` Initializes the object with the `homepage` of the browser.\n* `void visit(string url)` Visits `url` from the current page. It clears up all the forward history.\n* `string back(int steps)` Move `steps` back in history. If you can only return `x` steps in the history and `steps > x`, you will return only `x` steps. Return the current `url` after moving back in history **at most** `steps`.\n* `string forward(int steps)` Move `steps` forward in history. If you can only forward `x` steps in the history and `steps > x`, you will forward only `x` steps. Return the current `url` after forwarding in history **at most** `steps`.",
    "examples": [
        {
            "input": "10\nBrowserHistory leetcode.com\nvisit google.com\nvisit facebook.com\nvisit youtube.com\nback 1\nback 1\nforward 1\nvisit linkedin.com\nforward 2\nback 2\nback 7",
            "output": "null\nnull\nnull\nnull\nfacebook.com\ngoogle.com\nfacebook.com\nnull\nlinkedin.com\ngoogle.com\nleetcode.com",
            "explanation": "..."
        }
    ],
    "constraints": [
        "1 <= homepage.length <= 20",
        "1 <= url.length <= 20",
        "1 <= steps <= 100",
        "homepage and url consist of '.' or lower case English letters.",
        "At most 5000 calls will be made to visit, back, and forward."
    ],
    "publicTestCases": [
        {"input": "11\nBrowserHistory leetcode.com\nvisit google.com\nvisit facebook.com\nvisit youtube.com\nback 1\nback 1\nforward 1\nvisit linkedin.com\nforward 2\nback 2\nback 7", "expectedOutput": "null\nnull\nnull\nnull\nfacebook.com\ngoogle.com\nfacebook.com\nnull\nlinkedin.com\ngoogle.com\nleetcode.com"},
        {"input": "5\nBrowserHistory a.com\nvisit b.com\nvisit c.com\nback 2\nforward 1", "expectedOutput": "null\nnull\nnull\na.com\nb.com"},
        {"input": "4\nBrowserHistory z.com\nback 1\nforward 1\nvisit y.com", "expectedOutput": "null\nz.com\nz.com\nnull"}
    ],
    "hiddenTestCases": [
        {"input": "6\nBrowserHistory h.com\nvisit u1.com\nvisit u2.com\nvisit u3.com\nback 1\nvisit u4.com", "expectedOutput": "null\nnull\nnull\nnull\nu2.com\nnull"},
        {"input": "3\nBrowserHistory home.com\nback 10\nforward 10", "expectedOutput": "null\nhome.com\nhome.com"},
        {"input": "7\nBrowserHistory a.com\nvisit b.com\nvisit c.com\nback 1\nforward 1\nback 2\nvisit d.com", "expectedOutput": "null\nnull\nnull\nb.com\nc.com\na.com\nnull"},
        {"input": "4\nBrowserHistory foo.com\nvisit bar.com\nback 1\nforward 5", "expectedOutput": "null\nnull\nfoo.com\nbar.com"},
        {"input": "5\nBrowserHistory m.com\nvisit n.com\nback 2\nvisit o.com\nback 1", "expectedOutput": "null\nnull\nm.com\nnull\nm.com"}
    ],
    "starterCode": {
        "python": "import sys\n\nclass BrowserHistory:\n    def __init__(self, homepage: str):\n        pass\n    def visit(self, url: str) -> None:\n        pass\n    def back(self, steps: int) -> str:\n        pass\n    def forward(self, steps: int) -> str:\n        pass\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    obj = None\n    for i in range(1, n + 1):\n        parts = lines[i].split()\n        cmd = parts[0]\n        if cmd == 'BrowserHistory':\n            obj = BrowserHistory(parts[1])\n            print('null')\n        elif cmd == 'visit':\n            obj.visit(parts[1])\n            print('null')\n        elif cmd == 'back':\n            print(obj.back(int(parts[1])))\n        elif cmd == 'forward':\n            print(obj.forward(int(parts[1])))\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nclass BrowserHistory {\npublic:\n    BrowserHistory(string homepage) {}\n    void visit(string url) {}\n    string back(int steps) { return \"\"; }\n    string forward(int steps) { return \"\"; }\n};\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    BrowserHistory* obj = nullptr;\n    for (int i = 0; i < n; ++i) {\n        string cmd; cin >> cmd;\n        if (cmd == \"BrowserHistory\") {\n            string hp; cin >> hp;\n            obj = new BrowserHistory(hp);\n            cout << \"null\\n\";\n        } else if (cmd == \"visit\") {\n            string u; cin >> u;\n            obj->visit(u);\n            cout << \"null\\n\";\n        } else if (cmd == \"back\") {\n            int s; cin >> s;\n            cout << obj->back(s) << \"\\n\";\n        } else if (cmd == \"forward\") {\n            int s; cin >> s;\n            cout << obj->forward(s) << \"\\n\";\n        }\n    }\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\ntypedef struct {\n    \n} BrowserHistory;\n\nBrowserHistory* browserHistoryCreate(char * homepage) { return NULL; }\nvoid browserHistoryVisit(BrowserHistory* obj, char * url) {}\nchar * browserHistoryBack(BrowserHistory* obj, int steps) { return NULL; }\nchar * browserHistoryForward(BrowserHistory* obj, int steps) { return NULL; }\nvoid browserHistoryFree(BrowserHistory* obj) {}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    BrowserHistory* obj = NULL;\n    for (int i = 0; i < n; ++i) {\n        char cmd[20]; scanf(\"%s\", cmd);\n        if (strcmp(cmd, \"BrowserHistory\") == 0) {\n            char hp[100]; scanf(\"%s\", hp);\n            obj = browserHistoryCreate(hp);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"visit\") == 0) {\n            char u[100]; scanf(\"%s\", u);\n            browserHistoryVisit(obj, u);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"back\") == 0) {\n            int s; scanf(\"%d\", &s);\n            printf(\"%s\\n\", browserHistoryBack(obj, s));\n        } else if (strcmp(cmd, \"forward\") == 0) {\n            int s; scanf(\"%d\", &s);\n            printf(\"%s\\n\", browserHistoryForward(obj, s));\n        }\n    }\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass BrowserHistory {\n    public BrowserHistory(String homepage) {}\n    public void visit(String url) {}\n    public String back(int steps) { return \"\"; }\n    public String forward(int steps) { return \"\"; }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        BrowserHistory obj = null;\n        for (int i = 0; i < n; i++) {\n            String cmd = sc.next();\n            if (cmd.equals(\"BrowserHistory\")) {\n                obj = new BrowserHistory(sc.next());\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"visit\")) {\n                obj.visit(sc.next());\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"back\")) {\n                System.out.println(obj.back(sc.nextInt()));\n            } else if (cmd.equals(\"forward\")) {\n                System.out.println(obj.forward(sc.nextInt()));\n            }\n        }\n    }\n}"
    },
    "optimalSolutions": {
        "python": "import sys\n\nclass BrowserHistory:\n    def __init__(self, homepage: str):\n        self.history = [homepage]\n        self.curr = 0\n    def visit(self, url: str) -> None:\n        self.history = self.history[:self.curr + 1]\n        self.history.append(url)\n        self.curr += 1\n    def back(self, steps: int) -> str:\n        self.curr = max(0, self.curr - steps)\n        return self.history[self.curr]\n    def forward(self, steps: int) -> str:\n        self.curr = min(len(self.history) - 1, self.curr + steps)\n        return self.history[self.curr]\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    obj = None\n    for i in range(1, n + 1):\n        parts = lines[i].split()\n        cmd = parts[0]\n        if cmd == 'BrowserHistory':\n            obj = BrowserHistory(parts[1])\n            print('null')\n        elif cmd == 'visit':\n            obj.visit(parts[1])\n            print('null')\n        elif cmd == 'back':\n            print(obj.back(int(parts[1])))\n        elif cmd == 'forward':\n            print(obj.forward(int(parts[1])))\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nclass BrowserHistory {\n    vector<string> history;\n    int curr;\npublic:\n    BrowserHistory(string homepage) {\n        history.push_back(homepage);\n        curr = 0;\n    }\n    void visit(string url) {\n        history.resize(curr + 1);\n        history.push_back(url);\n        curr++;\n    }\n    string back(int steps) {\n        curr = max(0, curr - steps);\n        return history[curr];\n    }\n    string forward(int steps) {\n        curr = min((int)history.size() - 1, curr + steps);\n        return history[curr];\n    }\n};\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    BrowserHistory* obj = nullptr;\n    for (int i = 0; i < n; ++i) {\n        string cmd; cin >> cmd;\n        if (cmd == \"BrowserHistory\") {\n            string hp; cin >> hp;\n            obj = new BrowserHistory(hp);\n            cout << \"null\\n\";\n        } else if (cmd == \"visit\") {\n            string u; cin >> u;\n            obj->visit(u);\n            cout << \"null\\n\";\n        } else if (cmd == \"back\") {\n            int s; cin >> s;\n            cout << obj->back(s) << \"\\n\";\n        } else if (cmd == \"forward\") {\n            int s; cin >> s;\n            cout << obj->forward(s) << \"\\n\";\n        }\n    }\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n#define MAX_VAL(a, b) ((a) > (b) ? (a) : (b))\n#define MIN_VAL(a, b) ((a) < (b) ? (a) : (b))\n\ntypedef struct {\n    char** history;\n    int curr;\n    int size;\n    int capacity;\n} BrowserHistory;\n\nBrowserHistory* browserHistoryCreate(char * homepage) {\n    BrowserHistory* obj = (BrowserHistory*)malloc(sizeof(BrowserHistory));\n    obj->capacity = 5005;\n    obj->history = (char**)malloc(obj->capacity * sizeof(char*));\n    obj->history[0] = strdup(homepage);\n    obj->curr = 0;\n    obj->size = 1;\n    return obj;\n}\nvoid browserHistoryVisit(BrowserHistory* obj, char * url) {\n    for (int i = obj->curr + 1; i < obj->size; i++) free(obj->history[i]);\n    obj->curr++;\n    obj->history[obj->curr] = strdup(url);\n    obj->size = obj->curr + 1;\n}\nchar * browserHistoryBack(BrowserHistory* obj, int steps) {\n    obj->curr = MAX_VAL(0, obj->curr - steps);\n    return obj->history[obj->curr];\n}\nchar * browserHistoryForward(BrowserHistory* obj, int steps) {\n    obj->curr = MIN_VAL(obj->size - 1, obj->curr + steps);\n    return obj->history[obj->curr];\n}\nvoid browserHistoryFree(BrowserHistory* obj) {\n    for (int i = 0; i < obj->size; i++) free(obj->history[i]);\n    free(obj->history);\n    free(obj);\n}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    BrowserHistory* obj = NULL;\n    for (int i = 0; i < n; ++i) {\n        char cmd[20]; scanf(\"%s\", cmd);\n        if (strcmp(cmd, \"BrowserHistory\") == 0) {\n            char hp[100]; scanf(\"%s\", hp);\n            obj = browserHistoryCreate(hp);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"visit\") == 0) {\n            char u[100]; scanf(\"%s\", u);\n            browserHistoryVisit(obj, u);\n            printf(\"null\\n\");\n        } else if (strcmp(cmd, \"back\") == 0) {\n            int s; scanf(\"%d\", &s);\n            printf(\"%s\\n\", browserHistoryBack(obj, s));\n        } else if (strcmp(cmd, \"forward\") == 0) {\n            int s; scanf(\"%d\", &s);\n            printf(\"%s\\n\", browserHistoryForward(obj, s));\n        }\n    }\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass BrowserHistory {\n    List<String> history;\n    int curr;\n    public BrowserHistory(String homepage) {\n        history = new ArrayList<>();\n        history.add(homepage);\n        curr = 0;\n    }\n    public void visit(String url) {\n        while(history.size() > curr + 1) history.remove(history.size() - 1);\n        history.add(url);\n        curr++;\n    }\n    public String back(int steps) {\n        curr = Math.max(0, curr - steps);\n        return history.get(curr);\n    }\n    public String forward(int steps) {\n        curr = Math.min(history.size() - 1, curr + steps);\n        return history.get(curr);\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        BrowserHistory obj = null;\n        for (int i = 0; i < n; i++) {\n            String cmd = sc.next();\n            if (cmd.equals(\"BrowserHistory\")) {\n                obj = new BrowserHistory(sc.next());\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"visit\")) {\n                obj.visit(sc.next());\n                System.out.println(\"null\");\n            } else if (cmd.equals(\"back\")) {\n                System.out.println(obj.back(sc.nextInt()));\n            } else if (cmd.equals(\"forward\")) {\n                System.out.println(obj.forward(sc.nextInt()));\n            }\n        }\n    }\n}"
    },
    "tags": ["Array", "Linked List", "Stack", "Design", "Doubly-Linked List", "Data Stream"],
    "hints": ["Use an array to store the history and a pointer to track the current position.", "When visiting a new URL, discard all forward history by slicing the array."],
    "timeLimit": 2000,
    "memoryLimit": 256000
}

challenges.append(c49)

c50 = {
    "problemNumber": 50,
    "title": "Text Justification",
    "slug": "text-justification",
    "difficulty": "Hard",
    "category": "Mixed",
    "description": "Given an array of strings `words` and a width `maxWidth`, format the text such that each line has exactly `maxWidth` characters and is fully (left and right) justified.\n\nYou should pack your words in a greedy approach; that is, pack as many words as you can in each line. Pad extra spaces `' '` when necessary so that each line has exactly `maxWidth` characters.\n\nExtra spaces between words should be distributed as evenly as possible. If the number of spaces on a line does not divide evenly between words, the empty slots on the left will be assigned more spaces than the slots on the right.\n\nFor the last line of text, it should be left-justified, and no extra space is inserted between words.",
    "examples": [
        {
            "input": "7\nThis is an example of text justification.\n16",
            "output": "This    is    an\nexample  of text\njustification.  ",
            "explanation": "..."
        }
    ],
    "constraints": [
        "1 <= words.length <= 300",
        "1 <= words[i].length <= 20",
        "words[i] consists of only English letters and symbols.",
        "1 <= maxWidth <= 100",
        "words[i].length <= maxWidth"
    ],
    "publicTestCases": [
        {"input": "7\nThis is an example of text justification.\n16", "expectedOutput": "This    is    an\nexample  of text\njustification.  "},
        {"input": "6\nWhat must be acknowledgment shall be\n16", "expectedOutput": "What   must   be\nacknowledgment  \nshall be        "},
        {"input": "12\nScience is what we understand well enough to explain to a computer.\n20", "expectedOutput": "Science  is  what we\nunderstand      well\nenough to explain to\na computer.         "}
    ],
    "hiddenTestCases": [
        {"input": "1\nhello\n5", "expectedOutput": "hello"},
        {"input": "2\nhello world\n11", "expectedOutput": "hello world"},
        {"input": "3\na b c\n3", "expectedOutput": "a b\nc  "},
        {"input": "4\nListen to many, speak to a few.\n10", "expectedOutput": "Listen  to\nmany,     \nspeak to a\nfew.      "},
        {"input": "5\nGive me a place to stand\n10", "expectedOutput": "Give me  a\nplace   to\nstand     "}
    ],
    "starterCode": {
        "python": "import sys\n\ndef fullJustify(words, maxWidth):\n    pass\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    words = lines[1].split() if lines[1] else []\n    # if the words are space separated on line 2\n    maxWidth = int(lines[2])\n    ans = fullJustify(words, maxWidth)\n    for line in ans:\n        print(line)\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nvector<string> fullJustify(vector<string>& words, int maxWidth) {\n    return {};\n}\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    vector<string> words(n);\n    for(int i=0; i<n; ++i) cin >> words[i];\n    int maxWidth; cin >> maxWidth;\n    vector<string> ans = fullJustify(words, maxWidth);\n    for(const string& s : ans) cout << s << \"\\n\";\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nchar ** fullJustify(char ** words, int wordsSize, int maxWidth, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    char** words = (char**)malloc(n * sizeof(char*));\n    for(int i=0; i<n; ++i) {\n        char buf[50]; scanf(\"%s\", buf);\n        words[i] = strdup(buf);\n    }\n    int maxWidth; scanf(\"%d\", &maxWidth);\n    int rs;\n    char** ans = fullJustify(words, n, maxWidth, &rs);\n    for(int i=0; i<rs; ++i) {\n        printf(\"%s\\n\", ans[i]);\n        free(ans[i]);\n    }\n    free(ans); free(words);\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass Solution {\n    public List<String> fullJustify(String[] words, int maxWidth) {\n        return new ArrayList<>();\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        String[] words = new String[n];\n        for(int i=0; i<n; i++) words[i] = sc.next();\n        int maxWidth = sc.nextInt();\n        Solution sol = new Solution();\n        List<String> ans = sol.fullJustify(words, maxWidth);\n        for(String s : ans) System.out.println(s);\n    }\n}"
    },
    "optimalSolutions": {
        "python": "import sys\n\ndef fullJustify(words, maxWidth):\n    res, cur, num_of_letters = [], [], 0\n    for w in words:\n        if num_of_letters + len(w) + len(cur) > maxWidth:\n            for i in range(maxWidth - num_of_letters):\n                cur[i % (len(cur) - 1 or 1)] += ' '\n            res.append(''.join(cur))\n            cur, num_of_letters = [], 0\n        cur.append(w)\n        num_of_letters += len(w)\n    res.append(' '.join(cur).ljust(maxWidth))\n    return res\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if not lines: return\n    n = int(lines[0])\n    # The input words are all on line 1, separated by spaces\n    words = lines[1].split()\n    maxWidth = int(lines[2])\n    ans = fullJustify(words, maxWidth)\n    for line in ans:\n        print(line)\n\nif __name__ == '__main__':\n    main()",
        "cpp": "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nvector<string> fullJustify(vector<string>& words, int maxWidth) {\n    vector<string> res;\n    int n = words.size();\n    for(int i = 0; i < n; ) {\n        int j = i + 1, lineLen = words[i].length();\n        while(j < n && lineLen + 1 + words[j].length() <= maxWidth) {\n            lineLen += 1 + words[j].length();\n            j++;\n        }\n        string line = words[i];\n        int spaces = maxWidth - lineLen + (j - i - 1);\n        if (j == n || j - i == 1) {\n            for(int k = i + 1; k < j; k++) line += \" \" + words[k];\n            line += string(maxWidth - line.length(), ' ');\n        } else {\n            int spacesPerWord = spaces / (j - i - 1);\n            int extraSpaces = spaces % (j - i - 1);\n            for(int k = i + 1; k < j; k++) {\n                line += string(spacesPerWord + (k - i <= extraSpaces ? 1 : 0), ' ') + words[k];\n            }\n        }\n        res.push_back(line);\n        i = j;\n    }\n    return res;\n}\n\nint main() {\n    int n; if (!(cin >> n)) return 0;\n    vector<string> words(n);\n    for(int i=0; i<n; ++i) cin >> words[i];\n    int maxWidth; cin >> maxWidth;\n    vector<string> ans = fullJustify(words, maxWidth);\n    for(const string& s : ans) cout << s << \"\\n\";\n    return 0;\n}",
        "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nchar ** fullJustify(char ** words, int wordsSize, int maxWidth, int* returnSize) {\n    char** res = (char**)malloc(wordsSize * sizeof(char*));\n    *returnSize = 0;\n    for(int i = 0; i < wordsSize; ) {\n        int j = i + 1, lineLen = strlen(words[i]);\n        while(j < wordsSize && lineLen + 1 + strlen(words[j]) <= maxWidth) {\n            lineLen += 1 + strlen(words[j]);\n            j++;\n        }\n        char* line = (char*)malloc((maxWidth + 1) * sizeof(char));\n        line[0] = '\\0';\n        strcat(line, words[i]);\n        int spaces = maxWidth - lineLen + (j - i - 1);\n        if (j == wordsSize || j - i == 1) {\n            for(int k = i + 1; k < j; k++) {\n                strcat(line, \" \");\n                strcat(line, words[k]);\n            }\n            int len = strlen(line);\n            for(int k = len; k < maxWidth; k++) line[k] = ' ';\n            line[maxWidth] = '\\0';\n        } else {\n            int spacesPerWord = spaces / (j - i - 1);\n            int extraSpaces = spaces % (j - i - 1);\n            for(int k = i + 1; k < j; k++) {\n                int s = spacesPerWord + (k - i <= extraSpaces ? 1 : 0);\n                int len = strlen(line);\n                for(int m = 0; m < s; m++) line[len+m] = ' ';\n                line[len+s] = '\\0';\n                strcat(line, words[k]);\n            }\n        }\n        res[(*returnSize)++] = line;\n        i = j;\n    }\n    return res;\n}\n\nint main() {\n    int n; if (scanf(\"%d\", &n) != 1) return 0;\n    char** words = (char**)malloc(n * sizeof(char*));\n    for(int i=0; i<n; ++i) {\n        char buf[50]; scanf(\"%s\", buf);\n        words[i] = strdup(buf);\n    }\n    int maxWidth; scanf(\"%d\", &maxWidth);\n    int rs;\n    char** ans = fullJustify(words, n, maxWidth, &rs);\n    for(int i=0; i<rs; ++i) {\n        printf(\"%s\\n\", ans[i]);\n        free(ans[i]);\n    }\n    free(ans); free(words);\n    return 0;\n}",
        "java": "import java.util.*;\n\nclass Solution {\n    public List<String> fullJustify(String[] words, int maxWidth) {\n        List<String> res = new ArrayList<>();\n        for(int i = 0; i < words.length; ) {\n            int j = i + 1, lineLen = words[i].length();\n            while(j < words.length && lineLen + 1 + words[j].length() <= maxWidth) {\n                lineLen += 1 + words[j].length();\n                j++;\n            }\n            StringBuilder sb = new StringBuilder(words[i]);\n            int spaces = maxWidth - lineLen + (j - i - 1);\n            if (j == words.length || j - i == 1) {\n                for(int k = i + 1; k < j; k++) sb.append(\" \").append(words[k]);\n                while(sb.length() < maxWidth) sb.append(\" \");\n            } else {\n                int spacesPerWord = spaces / (j - i - 1);\n                int extraSpaces = spaces % (j - i - 1);\n                for(int k = i + 1; k < j; k++) {\n                    int s = spacesPerWord + (k - i <= extraSpaces ? 1 : 0);\n                    for(int m = 0; m < s; m++) sb.append(\" \");\n                    sb.append(words[k]);\n                }\n            }\n            res.add(sb.toString());\n            i = j;\n        }\n        return res;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        String[] words = new String[n];\n        for(int i=0; i<n; i++) words[i] = sc.next();\n        int maxWidth = sc.nextInt();\n        Solution sol = new Solution();\n        List<String> ans = sol.fullJustify(words, maxWidth);\n        for(String s : ans) System.out.println(s);\n    }\n}"
    },
    "tags": ["Array", "String", "Simulation"],
    "hints": ["Pack as many words as possible in each line.", "Calculate the spaces correctly depending on if it's the last line or not."],
    "timeLimit": 2000,
    "memoryLimit": 256000
}

challenges.append(c50)

with open('c:/Users/ram/Documents/Smart Coach/server/seed/challenges_queue_mixed.json', 'w') as f:
    # Read earlier generated variables and put them together
    import gen1, gen2, gen3, gen4
    all_challenges = []
    all_challenges.extend(gen1.challenges)
    all_challenges.extend(gen2.challenges)
    all_challenges.extend(gen3.challenges)
    all_challenges.extend(gen4.challenges)
    all_challenges.extend(challenges)
    json.dump(all_challenges, f, indent=2)

print("JSON generation complete")
